# Unsafe save:
# When it's true, stats will be saved when
# player leaves (when MySQL is enabled), or
# when server disables.
# However, when false, it will save when
# player finds a reward.
# -----------------------------------
# If hide-found-blocks is "NONE", it will
# be disabled.
# -----------------------------------
# For custom skulls for find effect,
# use head IDs from heads.freshcoal.com,
# what usually looks like this:
# eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzAxNDYxOTczNjM0NTI1MTk2ZWNjNzU3NjkzYjE3MWFkYTRlZjI0YWE5MjgzNmY0MmVhMTFiZDc5YzNhNTAyZCJ9fX0=

placeholderapi: false
use-mysql: false
enabled: false
disabled-msg: '&cBlocks aren''t enabled yet!'

use-uuid: true
check-full-inventory: 0
full-inventory-msg: '&c&lYour inventory is full!'

mysql-host: host
mysql-database: database
mysql-username: username
mysql-password: password
mysql-unsafe-save: true

no-permission: '&cYou don''t have permission for this!'

hide-found-blocks: NONE
blocks: []

find-block-commands:
    - msg %player% %pLocX% %pLocY% %pLocZ% %locX% %locY% %locZ%
    - msg %player% %blocksLeft% blocks left

all-blocks-found-commands:
    - msg %player% You found all blocks!
    - say %player% found all blocks!

already-found-commands:
    - msg %player% You already found this block!

already-found-all-blocks:
    - msg %player% You already found all blocks!

find-effect:
    enabled: true
    invisible: true
    small: true
    head: PUMPKIN
    chest: NONE
    leg: NONE
    boot: NONE
    particle: FLAME
    loop: 30
    levitation-per-loop: 0.2
    yaw-rotation: 20
    scheduler: 2
    y-start: 0.25
    sound: ENTITY_FIREWORK_LAUNCH
    pitch: 0

particles:
    loop: 20
    enabled: false
    found:
        dx: 0.05
        dy: 0.05
        dz: 0.05
        speed: 0.1
        quantity: 20
        type: DISABLED
    notfound:
        dx: 0.05
        dy: 0.05
        dz: 0.05
        speed: 0.1
        quantity: 35
        type: FLAME